### ISSUE TITLE
Listen to port 3000 instead of 8080

### ISSUE THREAD

**Issue by hirako2000** [sasha240100/between.js#26]
Many local env already listen to 8080.
Make rollup server listen to 3000 by default as it's a common dev port to use

**Comment by sasha240100** [comment]
@hirako2000 By the way, what's wrong with 8080? I guess it is aka default one

**Comment by hirako2000** [comment]
The problem with port 8080 is that:
- Some machines already listen to this port (as it's the default http port), rollup serve output stupidly fails without even saying it's because the port is already taken
- 8080 should be used for front facing production servers, not good practice for dev
- Dev common port to use is 3000, or 8000

We could use any arbitrary port, but anything is better than 8080.

**Comment by sasha240100** [comment]
@hirako2000 Merged
