### ISSUE TITLE
Add typings definition for TS consumers

### ISSUE THREAD

**Issue by hirako2000** [sasha240100/between.js#28]
The lib offers a relatively simple API, but would be nice to have typing definitions.
It will make it easier to pass the right params with autocomplete and have errors shown if typos or misuses are made.

![image](https://user-images.githubusercontent.com/1500712/43675613-251e3160-980d-11e8-9294-53bf4412174e.png)

**Comment by sasha240100** [comment]
@hirako2000 Merged. Close?
