### ISSUE TITLE
Infinitely emiting both 'update' and 'complete' events

### ISSUE THREAD

**Issue by panstav** [sasha240100/between.js#34]
[If you take the example code and run it](https://s.codepen.io/panstav/debug/rrgzWK/PNAvYGGQoyvr) with @0.1.1 you can see it's infinitely emiting both `update` and `complete` events.

Perhaps there's a `if (this[SYMBOL_COMPLETED]) return;` missing.

At first I wanted to PR a test to ensure that a Between instance that should run once would only emit the `complete` once and would not emit `update` afterwards, but was unsuccessful in running the tests locally. Would appreciate some help with that as well.

Thanks

**Comment by sasha240100** [comment]
@panstav Thanks for reporting! The codepen link returns 403 Error however, could you reupload it please?

**Comment by sasha240100** [comment]
Fixed in 043a9fa.

**Comment by panstav** [comment]
Perfect! Thanks a lot!
