### ISSUE TITLE
Problems with color plugin

### ISSUE THREAD

**Issue by panstav** [sasha240100/between.js#35]
First I thought it was only a matter of having `reqiure('between')` instead of `require('./between')` or `require('between.js')` at the between.js/build/dom-color.between.js file, but then I stumbled upon this less obvious error: `Uncaught TypeError: r.indexOf is not a function
    at Object.test`

[A CodePen showing this error](https://codepen.io/panstav/full/rrgzWK)

**Comment by sasha240100** [comment]
@panstav Hi! Thanks for reporting the issue! This was fixed in `v0.1.2-fix.2` version. Update your links:
- https://unpkg.com/between.js@0.1.2-fix.2/build/between.js
- https://unpkg.com/between.js@0.1.2-fix.2/build/dom-color.between.js
